[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "textual-thin-slider"
version = "0.1.0"
requires-python = ">= 3.8"
license = "MIT"
description = "A thin slider control widget for the Textual UI platform"
authors = [
    { name = "Robert Abram", email = "rabram991@gmail.com" },
]
dependencies = ["textual", ]
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = [
    "textual",
    "terminal",
    "widget",
    "slider",
    "ui"
]

[project.urls]
Homepage = "https://github.com/robabram/textual-thin-slider"
Repository = "https://github.com/robabram/textual-thin-slider"
Changelog = "https://github.com/robabram/textual-thin-slider"
Issues = "https://github.com/robabram/textual-thin-slider/issues"
